---
title: "esm204_hw3"
author: "David Segan"
date: "5/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r}
# ------------
# attach packages and read in csv
# ------------
library(tidyverse)
library(janitor)
library(stargazer)
library(wesanderson)
library(RColorBrewer)

# csv is demand of gasoline for high and low income consumer groups
gas_df <- read_csv("Homework 3 Data.csv") %>% 
  clean_names()


# add aggregate demand column
# convert gallons to thousands of gallons
gas_df_agg <- gas_df %>% 
  mutate(q_low_gallons = q_low_gallons) %>% 
  mutate(q_high_gallons = q_high_gallons) %>% 
  mutate(q_agg_gallons = q_low_gallons + q_high_gallons)
```

```{r}
# Assigning variables
gas_price <- 3
extern_country <- 1.5
extern_world <- 0.5
gas_tax <- 1

```

```{r}
# Linear models to estimate demand curves from data

# low income
lm_low <- lm(price_dollars ~ q_low_gallons, data = gas_df_agg)

# high income
lm_high <- lm(price_dollars ~ q_high_gallons, data = gas_df_agg)

# aggregate demand
lm_agg <- lm(price_dollars ~ q_agg_gallons, data = gas_df_agg)



```


```{r}
# # Piecewise aggregate demand function
# 
# # low income
# pw_lm_low <- lm(q_low_gallons ~ price_dollars, data = gas_df_agg)
# 
# # high income
# pw_lm_high <- lm(q_high_gallons ~ price_dollars, data = gas_df_agg)
# 
# #for piecewise, at what what quantity does the high_demand have a price equal to the low_demand y-intercept
# low_price <- lm_low$coefficients[1]
# dem_high_q <-function(p) {q = (p-lm_high$coefficients[1])/lm_high$coefficients[2]}
# 
# # this quantity = our change point
# change_point <- dem_high_q(low_price)
# 
# change_point
# 
# # make a list of possible gallons consumed
# p_gasoline <- seq(0,20, by = .5)
# # add it into a df
# p_gasoline_df <- data.frame(p_gasoline)
# # calculate demand at each p based off of models
# q_gasoline_agg <- p_gasoline_df %>% 
#   mutate(high_demand = pw_lm_high$coefficients[1] + pw_lm_high$coefficients[2]*p_gasoline) %>% 
#   mutate(low_demand = pw_lm_low$coefficients[1] + pw_lm_low$coefficients[2]*p_gasoline)
# 
# # set all negative values to 0
# q_gasoline_agg[q_gasoline_agg<0] <- 0
# 
# # calculate agg demand
# q_gasoline_agg <- q_gasoline_agg %>% 
#   mutate(agg_demand = high_demand + low_demand) %>% 
#   mutate(diff = agg_demand-change_point) %>%
#   mutate(dummy = ifelse(agg_demand>=change_point, 1, 0)) %>%
#   mutate(after_change_point = dummy*diff) %>% 
#   mutate(before_change_point = ifelse(agg_demand<=change_point, agg_demand, 0)) %>% 
#   mutate(after = ifelse(agg_demand>= change_point, agg_demand, 0))
# 
# # aggregate demand model
# pw_lm_agg <- lm(p_gasoline ~ agg_demand + after_change_point, data = q_gasoline_agg)
# 
# predict_df_pw <- predict(pw_lm_agg, q_gasoline_agg)
# 
# full_df_pw <- data.frame(q_gasoline_agg, predict_df_pw)
# 
# # gas_df_agg <- gas_df_agg %>%
# #   mutate(diff = q_agg_gallons-change_point) %>%
# #   mutate(dummy = ifelse(q_agg_gallons>=change_point, 1, 0)) %>%
# #   mutate(after_change_point = dummy*diff)
# # 
# # gas_agg_model_pw <- lm(price_dollars ~ q_agg_gallons + after_change_point, data = gas_df_agg)
# # 
# # gas_agg_model_pw
# 
# pw_lm_agg
```



```{r}
# If price equals $3, what quantity is demanded?

q_agg_eq <- (gas_price - lm_agg$coefficients[1])/lm_agg$coefficients[2]

q_low_eq <- (gas_price - lm_low$coefficients[1])/lm_low$coefficients[2]

q_high_eq <- (gas_price - lm_high$coefficients[1])/lm_high$coefficients[2]

# Supply curve
# Begins at $0 and 0 quantity, has a slope of 3/q_agg

gas_price/q_agg_eq

# make a list of possible gallons consumed
q_gasoline <- seq(0,600000, by = 10000)
# add it into a df
q_gasoline_df <- data.frame(q_gasoline)
# calculate marginal cost at each q (supply curve)
q_gasoline_supply <- q_gasoline_df %>% 
  mutate(mc = (gas_price/q_agg_eq)*q_gasoline)



```

```{r}
# Demand and supply functions p(q)

dem_low_p <- function(q) {p = lm_low$coefficients[1] + lm_low$coefficients[2]*q}
dem_high_p <-function(q) {p = lm_high$coefficients[1] + lm_high$coefficients[2]*q}
dem_agg_p <-function(q) {p = lm_agg$coefficients[1] + lm_agg$coefficients[2]*q}
supply_p <-function(q) {p = (gas_price/q_agg_eq)*q}
q <- 0:800000

q_agg_eq

# 
# # piecewise
# qlow <- 0:800000
# qhigh <- 0:800000
# qagg <- 0:800000
# p <- 0:20
# dem_low_q <-function(p) {qlow = (p-lm_low$coefficients[1])/lm_low$coefficients[2]}
# dem_high_q <-function(p) {qhigh = (p-lm_high$coefficients[1])/lm_high$coefficients[2]}
# 
# qlow+qhigh = ((p-lm_high$coefficients[1])/lm_high$coefficients[2])+(p-lm_low$coefficients[1])/lm_low$coefficients[2]
# 
# dem_agg_pw <- function(qagg) {p = gas_agg_model_pw$coefficients[1] + gas_agg_model_pw$coefficients[2]*q}
dem_agg_m <- function(q) {p = 14.5998 - (0.000019*q)}
dem_agg_pw <- function(q) {p = pw_lm_agg$coefficients[1] + pw_lm_agg$coefficients[2]*q + pw_lm_agg$coefficients[3]*q}

# Environmental cost functions

country_extern <- function(q) {p = extern_country}
world_extern <- function(q) {p = extern_world}
total_extern <- function(q) {p = extern_country+extern_world}

# Graph it!
  
ggplot() +
  stat_function(aes(q, color = "Low Income Demand"), fun = dem_low_p, size = 1, show.legend = TRUE) + 
  stat_function(aes(q, color = "High Income Demand"), fun = dem_high_p, size = 1, show.legend = TRUE) + 
  stat_function(aes(q, color = "Aggregate Demand"), fun = dem_agg_p, size = 1, show.legend = TRUE) +
  stat_function(aes(q, color = "Supply"), fun = supply_p, size = 1, show.legend = TRUE) +
  stat_function(aes(q, color = "Country Externality"), fun = country_extern, size = .4, show.legend = TRUE) + 
  stat_function(aes(q, color = "World Externality"), fun = world_extern, size = .4, show.legend = TRUE) +
  stat_function(aes(q, color = "Total Externality"), fun = total_extern, size = .4, show.legend = TRUE) +
  scale_y_continuous(limits = c(0,20),
                     expand = c(0,0)) +
  scale_x_continuous(labels = scales::comma,
                     expand = c(0,0)) +
  theme_light() +
  scale_color_brewer(palette = "Dark2") +
  labs(x = "Quantity (gallons)",
       y = "Price ($)",
       color = "Curves",
       title = "Domestic Gasoline Market")


```


```{r}
# Benefit to consumers and producers under this status quo, and environmental costs

agg_consumer_surplus <- integrate(dem_agg_p, lower = 0, upper = q_agg_eq)$value - (gas_price*q_agg_eq)

producer_surplus <- integrate(supply_p, lower = 0, upper = q_agg_eq)$value

low_consumer_surplus <- integrate(dem_low_p, lower = 0, upper = q_low_eq)$value - (gas_price*q_low_eq)

high_consumer_surplus <- integrate(dem_high_p, lower = 0, upper = q_high_eq)$value - (gas_price*q_high_eq)

agg_consumer_surplus <- low_consumer_surplus + high_consumer_surplus

world_environmental_cost <- extern_world * q_agg_eq

country_environmental_cost <- extern_country * q_agg_eq

# put these into a table
benefits_equilibrium <- c(agg_consumer_surplus, producer_surplus, low_consumer_surplus, high_consumer_surplus, world_environmental_cost, country_environmental_cost)

benefits_equilibrium

```

3. Tax of $1.00/gal

```{r}
# gas_tax = 1

# q_agg_tax <- ((gas_price+gas_tax) - lm_agg$coefficients[1])/lm_agg$coefficients[2]
# 
# q_agg_tax
# 
# supply_p_tax <-function(q) {p = gas_tax+(gas_price/q_agg_eq)*q}
# 
# # solve for q and p when new supply equals agg demand
# solve(gas_tax+(gas_price/q_agg_eq)*q, lm_agg$coefficients[1] + lm_agg$coefficients[2]*q)

# 3.a
# couldn't figure out how to solve for q after setting equal in r so used excel
q_tax <- 548449.42624834

# 3.b
# plug in new equilibrium quantity with tax into the demand equation to find the price
price_tax <- lm_agg$coefficients[1] + lm_agg$coefficients[2]*q_tax

price_tax

#3.c
# solve for quantity demanded by high income consumers after tax
q_high_tax <- (price_tax - lm_high$coefficients[1])/lm_high$coefficients[2]

# solve for surplus 
high_consumer_surplus_tax <- integrate(dem_high_p, lower = 0, upper = q_high_tax)$value - (price_tax*q_high_tax)

q_high_tax

high_consumer_surplus_tax

#3.d

q_low_tax <- (price_tax - lm_low$coefficients[1])/lm_low$coefficients[2]

low_consumer_surplus_tax <- integrate(dem_low_p, lower = 0, upper = q_low_tax)$value - (price_tax*q_low_tax)

low_consumer_surplus_tax

q_high_tax + q_low_tax

#3.e

producer_surplus_tax <- integrate(supply_p, lower = 0, upper = q_tax)$value

producer_surplus_tax

#3.f

country_damage_tax <- extern_country * q_tax

country_damage_tax

#3.g

world_damage_tax <- extern_world * q_tax

world_damage_tax

#3.h
# multiple gas tax($1) by the new equilibrium quantity 
total_revenue <- q_tax*gas_tax

total_revenue

```

4. Redistribution of tax

```{r}

```

5. Electric car shifts demand curves down by half

```{r}

# New demand is shifting down 0.5*original intercept
# Using solver in excel, new equilibrium quantity 293811.938

electric_car_q <- 293811.938

dem_agg_electric <-function(q) {p = 0.5*lm_agg$coefficients[1] + lm_agg$coefficients[2]*q}

electric_car_p <- dem_agg_electric(electric_car_q)
electric_car_p

# 5.a
q_high_electric <- (electric_car_p - (0.5*lm_high$coefficients[1]))/lm_high$coefficients[2]

q_high_electric

#5.b
q_low_electric <- (electric_car_p - (0.5*lm_low$coefficients[1]))/lm_low$coefficients[2]

q_low_electric

#5. c

electric_car_p

#5. d

local_damage_ecar <- extern_country * electric_car_q

local_damage_ecar

#5. e

world_damage_ecar <- extern_world * electric_car_q

world_damage_ecar
```

6. What gas tax makes local environmental quality equal to electric car

```{r}

# What tax causes aggregate quantity demanded to be same as electric_car_q

# Using excel solver
# Set supply equation with (electric_car_q) = aggregate demand equation with (electric_car_q) and solved for what tax makes them equal

# Tax of 7.5!!

```

